version: '3.8'

services:
  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=DbMeal
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - local-keycloak

  keycloak:
    depends_on:
      - postgres
    container_name: local_keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: DbMeal
      DB_USER: postgres
      DB_PASSWORD: postgres
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    image: jboss/keycloak:16.0.0
    ports:
      - "8080:8080"
      - "8443:8443"
    restart: unless-stopped
    networks:
      - local-keycloak

networks:
  local-keycloak: